---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ubinurse-watcher
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ubinurse-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ubinurse-watcher
subjects:
- kind: ServiceAccount
  name: ubinurse-watcher
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ubinurse-watcher
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - list
  - get
  - watch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubinurse-watcher
  name: ubinurse-watcher
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ubinurse-watcher
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ubinurse-watcher
    spec:
      containers:
      - image: registry-vpc.cn-hongkong.aliyuncs.com/haoshuwei/kubenurse-watcher
        imagePullPolicy: Always
        name: ubinurse-watcher
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: ubinurse-watcher